DROP TABLE IF EXISTS `PORTFOLIO_TRANSACTION`;
DROP TABLE IF EXISTS `PORTFOLIO`;
DROP TABLE IF EXISTS `INSTRUMENT`;
DROP TABLE IF EXISTS `INSTRUMENT_TYPE`;
DROP TABLE IF EXISTS `MARKET`;
DROP TABLE IF EXISTS `ID_TABLE`;

CREATE TABLE `MARKET` (
  `ID` int(10) NOT NULL,
  `SHORT_CODE` varchar(32) NOT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INSTRUMENT_TYPE` (
  `ID` int(10) NOT NULL,
  `NAME` varchar(128) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INSTRUMENT` (
  `ID` int(10) NOT NULL,
  `SYMBOL` varchar(64) NOT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `INSTRUMENT_TYPE_ID` int(10) DEFAULT NULL,
  `MARKET_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_INSTRUMENT_2` (`MARKET_ID`),
  KEY `FK_INSTRUMENT_1` (`INSTRUMENT_TYPE_ID`),
  CONSTRAINT `FK_INSTRUMENT_1` FOREIGN KEY (`INSTRUMENT_TYPE_ID`) REFERENCES `INSTRUMENT_TYPE` (`ID`),
  CONSTRAINT `FK_INSTRUMENT_2` FOREIGN KEY (`MARKET_ID`) REFERENCES `MARKET` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PORTFOLIO` (
  `ID` int(10) NOT NULL,
  `NAME` varchar(128) NOT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `LAST_MODIFY_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `PORTFOLIO_TRANSACTION` (
  `ID` int(10) NOT NULL,
  `INSTRUMENT_ID` int(10) NOT NULL,
  `TRANSACTION_DATE` datetime NOT NULL,
  `PRICE` int(10) NOT NULL,
  `PRICE_UNIT` varchar(32) NOT NULL,
  `CURRENCY` varchar(16) NOT NULL,
  `QUANTITY` int(10) NOT NULL,
  `COMMISSION_STAMP_DUTY` int(10) DEFAULT NULL,
  `COMMISSION_DEAL_FEE` int(10) DEFAULT NULL,
  `PORTFOLIO_ID` int(10) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PORTFOLIO_TRANSACTION_1` (`INSTRUMENT_ID`),
  KEY `FK_PORTFOLIO_TRANSACTION_2` (`PORTFOLIO_ID`),
  CONSTRAINT `FK_PORTFOLIO_TRANSACTION_1` FOREIGN KEY (`INSTRUMENT_ID`) REFERENCES `INSTRUMENT` (`ID`),
  CONSTRAINT `FK_PORTFOLIO_TRANSACTION_2` FOREIGN KEY (`PORTFOLIO_ID`) REFERENCES `PORTFOLIO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ID_TABLE` (
  `ID_NAME` varchar(128) NOT NULL,
  `ID_HI` int(10) NOT NULL,
  `ID_LO` int(10) NOT NULL DEFAULT '1',
  `INTERVAL` int(10) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('MARKET_ID', 0, 4, 1);
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('INSTRUMENT_ID', 0, 4, 1);
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('INSTRUMENT_TYPE_ID', 0, 4, 1);
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('PORTFOLIO_ID', 0, 4, 1);
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('PORTFOLIO_TRANSACTION_ID', 0, 16, 1);

